name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Install dependencies
        run: sudo apt-get install -y cmake g++ libgtest-dev

      - name: Build
        run: python scripts/build.py

      - name: Test
        run: ./build/tests/test_main

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: python scripts/deploy.py
